title: Me. Adriano Rodrigues
logo: /assets/img/logo.png
description:
  Engenheiro Eletricista <br>
  Desenvolvedor python <br>
  <br>
  Mestrado em Controle e Automação <br>
  Doutorando em controle e Automação <br>
  <br>
  <a href="https://www.linkedin.com/in/adrianordp/">Meu perfil LinkedIn</a> <br>
  <a href="https://www.github.com/adrianordp/">Meu perfil GitHub</a>
baseurl: ""
google_analytics:
theme: jekyll-theme-minimal