title: Me. Adriano Rodrigues
logo: /assets/img/adriano.png
description:
  Engenheiro Eletricista <br>
  Desenvolvedor Python <br>
  <br>
  Mestrado em Controle & Automação <br>
  Doutorando em Controle & Automação <br>
  <br>
  <a href="https://www.linkedin.com/in/adrianordp/">Meu perfil LinkedIn</a> <br>
  <a href="https://www.github.com/adrianordp/">Meu perfil GitHub</a>
baseurl: ""
google_analytics:
theme: jekyll-theme-minimal
plugins:
- jekyll-seo-tag